Repository bikezon/bikezon, pull requests merged in 2020-03, with the labels that each got.

#65 Frontend2
  app/forms.py
  app/migrations/0011_auto_20200320_1446.py
  static/css/main.css
  templates/app/feed.html
  templates/app/login.html
  templates/app/register.html
Labels: front-end

#70 initial tests for selling items
  .gitignore
  app/models.py
  templates/app/account.html
  templates/app/register.html
  templates/app/sell.html
  tests.py
Labels: deployment

#71 added tests for selling items
  app/forms.py
  app/models.py
  media/media/product_images/picture.png
  tests.py
Labels: deployment

#73 minor changes in css for selling items
  static/css/sell.css
  templates/app/sell.html
Labels: front-end

#74 drop down menu for account options
  static/css/index.css
  static/css/main.css
  static/js/app-js/account_button.js
  templates/app/base.html
  templates/app/index.html
Labels: enhancement, front-end

#101 README update
  README.md
Labels: enhancement

#135 Deployment
  app/admin.py
  app/models.py
Labels: enhancement
